### ISSUE TITLE
move market contract approve for all from app load to when making a listing

### ISSUE THREAD

**Issue by mchigit** [ryanprice/nft-market#77]

**Comment by ryanprice** [comment]
The flow of the app is confusing. The User is required to do 4 steps in order to successfully List an item.
Connect to the correct network - Moonbase alpha for now
Approve ALL - from the NFT contract - but is ONLY necessary for New listing, so let's move that action away from the default load and to the New listing page
Approve ZOOM spend - required for all listings
Create new listing - requires approval to complete.

The user needs to understand what state they are in, and what is next.
Lets layout UI that helps them understand

**Comment by prandev01** [comment]
If we remove the "Approve For All" when loading, we can't place a bid and settle the event now.
Please check it on the Contract code.
